### ISSUE TITLE
what is the diff between from char2word_qrn.py to char2word.py

### ISSUE THREAD

**Issue by SeekPoint** [yfletberliac/Mango#5]

**Comment by yfletberliac** [comment]
Please refer to the [README.md](https://github.com/yfletberliac/Mango/blob/master/README.md).

- char2word.py is just the implementation of the Char2Word encoder which takes text on character-level as input and transforms it into the same text on word-level. The module looks like following:
<img width="776" alt="screen shot 2017-09-14 at 11 48 21" src="https://user-images.githubusercontent.com/14262199/30423257-a40f1f9a-9942-11e7-94d8-848fb713583d.png">

- char2word_qrn.py is the implementation of the Query-Reduction Network using the Char2Word module instead of the [Position Encoding](https://arxiv.org/pdf/1503.08895.pdf) module.
